# Site settings
author: Mario Rodriguez
title: My Life in Code
header-img: img/home-bg.png
email: mario.rodriguez35@yahoo.com
copyright_name: Mario Rodriguez
description: > # this means to ignore newlines until "baseurl:"
  A Stay-at-Home Dad Turned Programmer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MRod21

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
